[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Lily Richards <lilymichellerichards@gmail.com>"]
edition = "2024"

[workspace.dependencies]
petgraph = "0.8.3"
